### ISSUE TITLE
don't play HLS

### ISSUE THREAD

**Issue by MG79NC** [rokudev/videoplayer-channel#3]
I can't get this player to play hls - m3u8 ? I have Roku ultra 7.5.1 build 4111 it plays mp4 fine but when I try to load a m3u8 it loads half way and stops loading, if I use my old legacy SDK player the m3u8 plays just fine.  will somebody help with this issue also I posted on Roku form and somebody confirmed my xml code was good so is something wrong with the example player for playing hls ?

https://forums.roku.com/viewtopic.php?f=34&t=100862

**Comment by MG79NC** [comment]
If you have m.port=CreateObject("roMessagePort") in the "Showheroscreen" function in main.brs, immediately followed by screen.setMessagePort(m.port) then I think you'll need to wait for the next release of the firmware as this ought to be fixed when you get that.


that's what somebody said on the forum the problem is so this video player don't work right on a Roku ultra ? so I have to wait till I get a firmware in order for this example player to work correct I guess?

**Comment by dannykng** [comment]
Can you provide a link to your xml feed? I'm not able to replicate the issues you're experiencing.

You can bypass having a fully working feed by changing [ContentNode.url](https://github.com/rokudev/videoplayer-channel/blob/master/components/SpringBoard.brs#L40) and [ContentNode.streamFormat](https://github.com/rokudev/videoplayer-channel/blob/master/components/SpringBoard.brs#L39) in [Springboard.brs](https://github.com/rokudev/videoplayer-channel/blob/master/components/SpringBoard.brs) to the NASA stream:

```
ContentNode.url = "http://nasatv-lh.akamaihd.net/i/NASA_101@319270/index_1000_av-p.m3u8"
ContentNode.streamFormat = "hls" 
```

This will hardcode the NASA stream so it doesn't matter which content item you select in the channel.

**Comment by MG79NC** [comment]
http://rlcevg.com/rokuplayer/xml/categories.xml

if I test the same xml file with legacy sdk player everything works good...
if I test the m3u8 with the multi live channel example they play good...

when I test this videoplayer- channel player which is the one I really would like to use it don't work.

this is all it does loads half way and stops  I took picture for you.
http://rlcevg.com/rokuplayer/xml/testm3u8.jpg


it does play mp4 just fine just not playing hls I would like to setup categories for mp4 and one for hls but I have failed to get hls to play with this player on Roku ultra

**Comment by dannykng** [comment]
Thanks for the info! It looks like streamFormat was not being parsed correctly in this sample. I just added a fix so please try again and let me know if there are any issues.

**Comment by MG79NC** [comment]
Tested and now it works THANK YOU tested with mp4 and m3u8 both is working good I'm really greatful for you fast help with this issue.. :)
